# Generated by Django 2.2.1 on 2019-10-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('run', 'Running'), ('bike', 'Biking'), ('elipitical', 'Eliptical'), ('other', 'Other')], help_text='The type of cardio you did.', max_length=15)),
                ('duration', models.PositiveSmallIntegerField(verbose_name='How long you performed this cardio for.')),
                ('distance_in_miles', models.DecimalField(decimal_places=2, help_text='Distance traveled.', max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(help_text='The name of the workout you did.', max_length=50)),
                ('sets', models.PositiveSmallIntegerField(help_text='The number of sets you attempted.')),
                ('reps', models.PositiveSmallIntegerField(help_text='The number of reps you attempted for each set.')),
                ('success', models.BooleanField(help_text='Did you hit your sets and reps?')),
            ],
        ),
    ]
