# Generated by Django 2.2.1 on 2019-10-16 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(help_text='The name of the workout you did.', max_length=50)),
                ('sets', models.PositiveSmallIntegerField(help_text='The number of sets you attempted.')),
                ('reps', models.PositiveSmallIntegerField(help_text='The number of reps you attempted for each set.')),
                ('weight', models.PositiveSmallIntegerField(help_text='The weight that you attempted.')),
                ('sets_successful', models.PositiveSmallIntegerField(help_text='The number of sets you completed succesfuly.')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Date of exercise.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cardio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('run', 'Running'), ('bike', 'Biking'), ('elipitical', 'Eliptical'), ('other', 'Other')], help_text='The type of cardio you did.', max_length=15)),
                ('duration', models.PositiveSmallIntegerField(help_text='How long you performed this cardio for.')),
                ('distance_in_miles', models.DecimalField(decimal_places=2, help_text='Distance traveled.', max_digits=2)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Date of exercise.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
