# Generated by Django 2.2.1 on 2019-10-08 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardio',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=1, help_text='Date of exercise.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardio',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=1, help_text='Date of exercise.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardio',
            name='duration',
            field=models.PositiveSmallIntegerField(help_text='How long you performed this cardio for.'),
        ),
    ]
