# Generated by Django 3.0 on 2019-12-04 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardio',
            old_name='duration',
            new_name='duration_in_minutes',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='weight',
            new_name='weight_in_pounds',
        ),
    ]
