# Generated by Django 3.1 on 2019-11-12 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0003_auto_20191016_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Date of meal.')),
                ('type', models.CharField(choices=[('fat', 'Fat'), ('carb', 'Carb'), ('protein', 'Protein')], help_text='Calorie Type', max_length=15)),
                ('count', models.PositiveSmallIntegerField(help_text='Calories (g)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
