# Generated by Django 3.1 on 2019-11-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_nutrition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardio',
            name='distance_in_miles',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='cardio',
            name='duration',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cardio',
            name='type',
            field=models.CharField(choices=[('run', 'Running'), ('bike', 'Biking'), ('elipitical', 'Eliptical'), ('other', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='grams',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='type',
            field=models.CharField(choices=[('fat', 'Fat'), ('carb', 'Carb'), ('protein', 'Protein')], max_length=15),
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercise_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='workout',
            name='reps',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='workout',
            name='sets',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='workout',
            name='sets_successful',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='workout',
            name='weight',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
